### ISSUE TITLE
PHP Warning: is_dir(): open_basedir restriction in effect. File(/) is not within the allowed path

### ISSUE THREAD

**Issue by nebrot** [Zillion01/jpfaq#10]
![jpfaq-typoscript-bug](https://user-images.githubusercontent.com/6941112/32284839-c9c1116a-bf28-11e7-84f3-d4c3424e8244.png)

The error is thrown multiple times on every request because of empty constants for the templates (see https://github.com/Zillion01/jpfaq/blob/master/Configuration/TypoScript/constants.ts#L2-L9 ).
You could set constants for example like powermail (see https://github.com/einpraegsam/powermail/blob/develop/Configuration/TypoScript/Main/constants.txt#L4-L13), so that it's working without defining custom-constants or setup.

I can create a PR if you want.

TYPO3 8.7.8
PHP 7.0
jpfaq 8.7.0

**Comment by Zillion01** [comment]
Thanks, I did not encounter this bug once, however I set default values in 8.7.1. Should be in the TER now.

**Comment by nebrot** [comment]
Thank you, the commit fix the problems! Keep up the great work.
