### ISSUE TITLE
lost functionality in Version 8.7.1

### ISSUE THREAD

**Issue by baggyownz** [Zillion01/jpfaq#11]
I miss the variable "category" and "categoryUid" in template "Question/List.html". The variables doesn't filled (anymore) in last version in QuestionController.

**Comment by Zillion01** [comment]
The template should indeed be updated. However if you want to output category info, you could edit the template. Within 

`<f:for each="{questions}" as="question">`

You can do for example

```
<f:for each="{question.categories}" as="item">
     {item.category}
</f:for>
```

**Comment by baggyownz** [comment]
Thank you for your fast answer.
Yes it's possible. But it would be nice if these variables are filled too. :-)
Then you could use them for subdivisions.

`<h2 class="jpfaqCategory">{category}</h2>`

`<div class="listCategory{categoryUid}">`

I've found another way and use normal headlines for subdivision. 

Thank you again.

**Comment by Zillion01** [comment]
Well then the question remains how to order and output the FAQ records. A FAQ record can have multiple categories. I am open for suggestions.
