### ISSUE TITLE
Publish package on packagist.org

### ISSUE THREAD

**Issue by christian-fries** [Zillion01/jpfaq#16]
It would be nice if you could add the package to [packagist.org](https://packagist.org) and add tags to the releases so it could be installed via composer without the usage of the fake vendor "typo3-ter".

**Comment by Zillion01** [comment]
Hi, sry I am extremely busy. Can you show explain me how to do this? Thx

**Comment by christian-fries** [comment]
It can be accomplished in 4 easy steps:

1. Remove the "version" property from your `composer.json` file. Versions are defined by tagging commits or [creating releases](https://help.github.com/en/articles/creating-releases) on github.
2. [Submit your repository](https://packagist.org/packages/submit) on packagist. You can log in with your github account.
3. [Set up a webhook](https://packagist.org/about#how-to-update-packages) so packagist is updated whenever you push a new commit to github.
4. Add a tag/release to your code

Once you've added the repository to packagist, the latest stable version of the extension can be installed by running `composer require jp/jpfaq`.

**Comment by Starkmann** [comment]
Stumbled over this as well.
The extension is at the moment only installable requiring the branches. 
So tagging would be nice. Then extension would also be installable via composer.typo3.org.

**Comment by Starkmann** [comment]
Have made 2 PR for this. But tagging is not part of it.
See here:
https://github.com/Starkmann/jpfaq/releases

**Comment by Zillion01** [comment]
Hey thanks for your contributions. It seems the jp namespace is already taken at Packagist, does this mean I need to rename this in all PHP files and the composer.json file? Thanks

**Comment by Zillion01** [comment]
Thanks all, it is working now.
composer require jvdp/jpfaq

**Comment by Starkmann** [comment]
Thank you.
Can you also make a relase/tag for typo3 8.7.
```
composer require jvdp/jpfaq
```
This will fails under typo3 8.7

You can tag 8.8.2 on HEAD of TYPO3-7.6-and-8.7 as i did.

**Comment by Zillion01** [comment]
Added 8.8.3 too now. Thx
