### ISSUE TITLE
Possibility to add files and images

### ISSUE THREAD

**Issue by christian-fries** [Zillion01/jpfaq#2]
Hi

I'm currently evaluating different FAQ extensions for modern TYPO3 Versions (7.6+) and I just tested your extension, it looks quite good. One requirement for me is to have the possibility to add files/downloads and images.

Could you imagine adding those fields? Or: If I'd create a pull request with some additional TCA for assets and images, would you review and possibliy merge that changes? 

Kind regards
Chris

**Comment by Zillion01** [comment]
hi!

I will change the Answer field into tt_content IRRE. Then you can add whatever you want there. In a couple days.

**Comment by christian-fries** [comment]
Sounds good to me. Can I help you somehow?

**Comment by Zillion01** [comment]
Hi Chris,

I updated the source here. I did not really test, could you please test and let me know if you see any needed improvements. If ok I upload to repository.

**Comment by Zillion01** [comment]
I uploaded it to the repository

**Comment by christian-fries** [comment]
Thanks for the update! 
There are some copy paste errors in the new code:
- TCA foreign_field is set to "venues" which doesn't extist.
- Property $additionalContentAnswer is of type 
@var \TYPO3\CMS\Extbase\Persistence\ObjectStorage<\Jp\ThcbVenues\Domain\Model\TtContent> which is the wrong namespace (ThcbVenues)

**Comment by Zillion01** [comment]
Dang, thanks! LOL I must have been asleep still. Fixed it and uploaded to repo.
