### ISSUE TITLE
Show/hide "+ Show all Answers"

### ISSUE THREAD

**Issue by webdev2027** [Zillion01/jpfaq#21]
Hi, there. after creating a new FAQ, there's always "+ Show all answers / Hide"-button above the FAQ. At the moment I will hide it with Styles.

It would be nice, If I can show/hide this message with a TCA-Checkbox. I'm still using v8.8.3. Thanks a lot.

**Comment by Zillion01** [comment]
Hi, if you don't like this, you can remove it from the template.
