### ISSUE TITLE
TYPO3 10 compatibility

### ISSUE THREAD

**Issue by p380** [Zillion01/jpfaq#24]
Hi!
Are there any plans about making extension compatible to TYPO3 10 LTS?

**Comment by Zillion01** [comment]
Yes, but no time for now. You can shoot in a pull request, shouldnt be too hard.

**Comment by christian-fries** [comment]
I created the pull request https://github.com/Zillion01/jpfaq/pull/25 providing support for TYPO3 9.5 and 10.4.

**Comment by Zillion01** [comment]
Thank a lot, released!
