### ISSUE TITLE
Class 'TYPO3\CMS\Core\Information\Typo3Version' not found

### ISSUE THREAD

**Issue by geri777** [Zillion01/jpfaq#27]
Right after installation of the current version (10.4.0) on Typo3 version 9.5.11 the website crashes (BE+FE) with the following error message: Class 'TYPO3\CMS\Core\Information\Typo3Version' not found.

![image](https://user-images.githubusercontent.com/4689190/94006857-c894a180-fda0-11ea-8577-e60d953bcf83.png)

I think the class Typo3Version has been introduced in Typo3 v10 - however the repository indicates this version should workon Typo3 9 as well.

**Comment by Zillion01** [comment]
Hi, 9.5.11 is very outdated. It's in 9.5 see https://forge.typo3.org/issues/90907
