### ISSUE TITLE
Category relationship is broken

### ISSUE THREAD

**Issue by tobenschmidt** [Zillion01/jpfaq#3]
The extension uses table *sys_category_record_mm* for its relationship between its custom categories and questions. But it leaves the fields *tablenames* and *fieldname* empty.

This is probably the reason why everytime I add a new question all entries in *sys_category_record_mm* with the uid of the question in field *uid_local* are deleted.

It also looks like your using *uid_local* for the question und *uid_foreign* for the category. It has to be vice versa.

**Comment by tobenschmidt** [comment]
Looks like that at least the following TCA configuration for the *categories* field in *tx_jpfaq_domain_model_question.php* is missing:

```php
'MM_match_fields' => [
    'fieldname' = 'categories'
    'tablenames' = 'tx_jpfaq_domain_model_question'
]
```

**Comment by Zillion01** [comment]
Thank you, that was indeed messed up. I removed sys_category and added tx_jpfaq_question_category_mm

Upped to repo 8.5.2

**Comment by tobenschmidt** [comment]
Thanks for the quick fix. I can confirm that the category relationship works in version 8.5.2. It does not delete system category relationships anymore.
