### ISSUE TITLE
Feature Request: TYPO3 system categories to structure FAQs by category

### ISSUE THREAD

**Issue by Hobokens** [Zillion01/jpfaq#30]
Please use TYPO3 system categories to structure FAQs by category.

**Comment by Zillion01** [comment]
Yup that a bitch, sponsor and I make

**Comment by Zillion01** [comment]
Not sure if it has improved now, but I once dove into this, and when I saw what kinda hacks Georg needed to write for EXT:News, I was not that motivated anymore
