### ISSUE TITLE
Important function: Accessibility

### ISSUE THREAD

**Issue by uv21** [Zillion01/jpfaq#32]
Is there an easy way to make the FAQ dropdowns accessible, so that the accordion items can be jumped to via TAB key and opened/closed with ENTER or arrow down/arrow up key?

**Comment by Zillion01** [comment]
You can put the template local, overwrite the path to the template with typoscript and Google how to use TAB key by adding a simple attribute to the HTML. Anyways if you make it, shoot in a pull request I add it. Good luck ;)
