### ISSUE TITLE
TYPO3 11LTS compatible version

### ISSUE THREAD

**Issue by dkd-janke** [Zillion01/jpfaq#35]
Hello,

are there any concrete plans to release a version compatible with TYPO3 11LTS?

Greetings Thomas

**Comment by Zillion01** [comment]
Hi, yes coming weeks I will work on it.

**Comment by dkd-janke** [comment]
> Hi, yes coming weeks I will work on it.

Thank you for your commitment to the TYPO3 project! We will plan with the further use of jpfaq under TYPO3 11LTS.

**Comment by Zillion01** [comment]
An alpha version is on the DEV branche. Works reasonably already on 11 LTS. Takes some more optimizations like deprecated TCA. Also templates will be updated for accessibility.  When I got time I will work further on it.

**Comment by Zillion01** [comment]
Released
