### ISSUE TITLE
Is there a way to prevent spam comments?

### ISSUE THREAD

**Issue by iunctim** [Zillion01/jpfaq#37]
I'm using jpfaq 10.4.1 with category and question comments activated. Unfortunately I frequently receive spam entries in both tx_jpfaq_domain_model_categorycomment and tx_jpfaq_domain_model_questioncomment, like e.g.
`497 | 2022-02-02 08:57:56   | 1zqjnw'"(){}<x>:/1zqjnw;9 `
Is there a way to prohibit such comments being written? Could I easily integrate some captcha or something similar?
Thanks in advance!

**Comment by Zillion01** [comment]
Hmm, apparently the honey pot does not work good enough then.. you mind sharing or emailing me the URL? Didn't have any complaints about this before.

We could build in a captcha.. feel free to sponsor.

**Comment by iunctim** [comment]
Thanks for the quick response, I just sent you a mail.
