### ISSUE TITLE
Undefined array key module

### ISSUE THREAD

**Issue by MSPTYPO3** [Zillion01/jpfaq#38]
Related to this : Configuration/TsConfig/Page/pageTSconfig.tsconfig

Every time you click on a module, error is generated:

Core: Error handler (BE): PHP Warning: Undefined array key "module" in /var/www/SERVER/vendor/symfony/expression-language/Node/GetAttrNode.php line 97

Typo3 11.5.8
jpFAQ: 11.5.0
PHP : 8.0.8

**Comment by Zillion01** [comment]
Cannot reproduce. Using the TYPO3 Bootstrap sitepackage. https://www.sitepackagebuilder.com/

Typo3 11.5.8
jpFAQ: 11.5.0
PHP : 8.0.8

This does not seem to be related to jpFaq. You could try Slack or Stackoverflow for assistence.
