### ISSUE TITLE
TYPO3 11 and PHP 7.4 compatibility

### ISSUE THREAD

**Issue by tobikummer** [Zillion01/jpfaq#41]
**Setup:**
TYPO3 11.5.22
Extension version: 11.6.0
PHP 7.4.30

**Error**

(1/1) ParseError
syntax error, unexpected '|', expecting ';' or '{'

in /var/www/html/web/typo3conf/ext/jpfaq/Classes/Controller/QuestionController.php line 129
     *
     * @throws IllegalObjectTypeException
     * @throws UnknownObjectException
     */
    public function helpfulnessAction(Question $question, bool $helpful, int $pluginUid): ResponseInterface|ForwardResponse
    {

_ResponseInterface|ForwardResponse_ is not valid in PHP 7.4. Don't know if there are more occurrences, stumbled over this one...

**Comment by dermatthias** [comment]
Ran into this as well. Typo3 11.5 has a minimum requirement of 7.4, but this Controller uses a PHP 8.0+ feature (union return types).

**Comment by Zillion01** [comment]
Hi, I will look into this, meanwhile you can also shoot in a pull request

**Comment by tobikummer** [comment]
https://github.com/Zillion01/jpfaq/pull/42

**Comment by Zillion01** [comment]
11.6.2 Has been released. Thank you for the pull request @tobikummer
