### ISSUE TITLE
Improve schema.org notation

### ISSUE THREAD

**Issue by Zillion01** [Zillion01/jpfaq#44]
Test the faq at https://search.google.com/test/rich-results and improve the schema.org notation in the templates

**Comment by brotkrueml** [comment]
But keep in mind: Not every FAQ qualifies for structured data: https://developers.google.com/search/docs/appearance/structured-data/faqpage?hl=en#content-guidelines

"If you have FAQ content that is repetitive on your site (meaning, the same question and answer appear on multiple pages on your site), mark up only one instance of that FAQ for your entire site."

**Comment by Zillion01** [comment]
This has been improved in 12.4
