### ISSUE TITLE
search form -> return/submit

### ISSUE THREAD

**Issue by webdev2027** [Zillion01/jpfaq#5]
If an user insert a search phrase and press enter, the form will submit and redirect to homepage.
I understand, that the search results are loading automatically, but maybe some users don't.

I'm using ` onsubmit="return false;"` in partial `SearchForm.html`

**Comment by Zillion01** [comment]
Hi, thanks for your suggestion. In a next release I will add some js for this.

**Comment by webdev2027** [comment]
great, thanks.

**Comment by nebrot** [comment]
Anything new for this issue? A new release with this fix would be nice :-)

**Comment by Zillion01** [comment]
I updated to 8.7.1 in repo. Cheers
