### ISSUE TITLE
can't localize additional content 

### ISSUE THREAD

**Issue by smclic** [Zillion01/jpfaq#6]
Hi. It's not possible to localize the additional content (in Typo3 7.6.18).
I use it only to insert a picture. It would also be great if You could integrate a picture to the normal answer.

**Comment by Zillion01** [comment]
I just verified this on 7.6.18 with the introduction package and jpFAQ 8.5.2
It works. Just use list view in the folder records and localise the additional tt_content record (for example Text and Media). After that clear cache. You need to make a localised version of the questions folder too.

**Comment by smclic** [comment]
8.7.0
