### ISSUE TITLE
Translation error on french 

### ISSUE THREAD

**Issue by snfbridge** [Zillion01/jpfaq#7]
The translation for "Show all answers" in French isn't "Afficher toutes les résponses" but "Afficher tout les réponses". If I change the translation on "fr.locallang.xlf" <trans-unit id="jpfaq_showAll"><target>Afficher toutes les rÃ©ponses</target> the error resists on frontend. Where can I change the translation for it?

Thanx!

**Comment by Zillion01** [comment]
Hi

I will change your translation on Github.

If you change a language file anf it won't show --> cache. 
https://kronova.net/tutorials-codeschnipsel/typo3/typoscript/typo3-flush-system-caches-aktivieren.html

plugin.tx_jpfaq._LOCAL_LANG.fr {
  jpfaq_showAll = I am going to learn Google
}

https://wiki.typo3.org/TypoScript_language_additions,_override

**Comment by snfbridge** [comment]
Hi

Thank you! Perfect.

Kind regards,
Mark


Von: Jacco van der Post [mailto:notifications@github.com]
Gesendet: Freitag, 30. Juni 2017 11:00
An: Zillion01/jpfaq <jpfaq@noreply.github.com>
Cc: Christen Mark <mark.christen@snf.ch>; Author <author@noreply.github.com>
Betreff: Re: [Zillion01/jpfaq] Translation error on french (#7)


Hi

I will change your translation on Github.

If you change a language file anf it won't show --> cache.
https://kronova.net/tutorials-codeschnipsel/typo3/typoscript/typo3-flush-system-caches-aktivieren.html

plugin.tx_jpfaq._LOCAL_LANG.fr {
jpfaq_showAll = I am going to learn Google
}

https://wiki.typo3.org/TypoScript_language_additions,_override
