### ISSUE TITLE
Bug in constants.ts

### ISSUE THREAD

**Issue by agendartobias** [Zillion01/jpfaq#8]
Hello i found a bug in your file constants.ts (path: typo3conf/ext/jpfaq/Configuration/TypoScript)

When i defined local template it didn't work. Because of 1st line: **plugin.tx_jpfaq_faq** (definition of module must be: **plugin.tx_jpfaq**

**So FULL code with bug:**

plugin.tx_jpfaq_faq {
    view {
        # cat=plugin.tx_jpfaq_faq/file; type=string; label=Path to template root (FE)
        templateRootPath =
        # cat=plugin.tx_jpfaq_faq/file; type=string; label=Path to template partials (FE)
        partialRootPath =
        # cat=plugin.tx_jpfaq_faq/file; type=string; label=Path to template layouts (FE)
        layoutRootPath =
    }
}

**FIXED CODE:**
plugin.tx_jpfaq {
    view {
        # cat=plugin.tx_jpfaq_faq/file; type=string; label=Path to template root (FE)
        templateRootPath =
        # cat=plugin.tx_jpfaq_faq/file; type=string; label=Path to template partials (FE)
        partialRootPath =
        # cat=plugin.tx_jpfaq_faq/file; type=string; label=Path to template layouts (FE)
        layoutRootPath =
    }
}

I hope it helps you :) Now local templates works 💃

**Comment by Zillion01** [comment]
Hey I am sry but it does not. In typoscript you see that it refers to plugin.tx_jpfaq_faq:

plugin.tx_jpfaq_faq {
    view {
        templateRootPaths.0 = EXT:jpfaq/Resources/Private/Templates/
        templateRootPaths.1 = {$plugin.tx_jpfaq_faq.view.templateRootPath}

jpFAQ 8.7.0
