### ISSUE TITLE
Permission to add questions for user role "editor"

### ISSUE THREAD

**Issue by snfbridge** [Zillion01/jpfaq#9]
Where can I set the permission to add questions for the user role "Editor"? Actually, I can only add and modify entries by using the rule "Administrator".

Best regards and thank you for your help!
Mark

**Comment by Zillion01** [comment]
In the usergroup of editors , access lists, you can like normal content elements allow access.

grts Jacco

**Comment by snfbridge** [comment]
Thanks! It's difficult to see cause the fields don't have a distinct mapping by name for the extension.
